import { nanoid } from 'nanoid';

const products = [
  {
    id: nanoid(),
    name: 'Joystick Game Controller',
    description: ' Wired UCOM USB Pad for PC',
    rating: 5,
    favorite: false,
    price: 11250,
    category: 'tech',
  },
  {
    id: nanoid(),
    name: 'Apple IPhone 14 Pro',
    description: '6GB RAM + 128GB ROM',
    rating: 5,
    favorite: false,
    price: 1450000,
    category: 'tech',
  },
  {
    id: nanoid(),
    name: 'Touch Screen Smart Watch',
    description: 'For Andriod & IOS',
    rating: 5,
    favorite: true,
    price: 9170,
    category: 'tech',
  },
  {
    id: nanoid(),
    name: 'Itel Bluetooth Earphones',
    description: 'BUDS ACE Wireless Earphone',
    rating: 4,
    favorite: false,
    price: 17660,
    category: 'tech',
  },
  {
    id: nanoid(),
    name: 'HP ENVY 15 X360',
    description: 'INTEL Core i7 16GB RAM 512 SSD.....',
    rating: 5,
    favorite: false,
    price: 1300000,
    category: 'tech',
  },
  {
    id: nanoid(),
    name: 'Oriamo 2000mAh PowerBank',
    description: 'Type-C & Micro-USB input Fast Charge..',
    rating: 4,
    favorite: false,
    price: 19999,
    category: 'tech',
  },
  // * MEN
  {
    id: nanoid(),
    name: `Men’s Belt Leather`,
    description: 'Buckle Brown Timeless Belt ',
    rating: 4,
    favorite: false,
    price: 17500,
    category: 'tech',
  },
  {
    id: nanoid(),
    name: `Quality Plain Face Cap`,
    description: 'Plain Black Face Cap',
    rating: 5,
    favorite: false,
    price: 4000,
    category: 'men',
  },
  {
    id: nanoid(),
    name: `Men’s Formal Lace Up Shoes`,
    description: 'Italian Brogues Leather Shoes',
    rating: 4,
    favorite: false,
    price: 21000,
    category: 'men',
  },
  {
    id: nanoid(),
    name: `Men’s Short Sleeve`,
    description: 'Casual Shirt - Black & Brown',
    rating: 5,
    favorite: false,
    price: 25900,
    category: 'men',
  },
  {
    id: nanoid(),
    name: `Men’s Three Piece Tuxedo`,
    description: 'Elegant Wedding Suit - Teal Green',
    rating: 4,
    favorite: false,
    price: 65990,
    category: 'men',
  },
  {
    id: nanoid(),
    name: `DesubClassic Quality Agbada`,
    description: 'Black Agbada with a Black inner Top',
    rating: 4,
    favorite: false,
    price: 85000,
    category: 'men',
  },
  // * WOMEN
  {
    id: nanoid(),
    name: `Ladies Leather Chic Bag`,
    description: 'Office Trendy Handbag - Brown',
    rating: 4,
    favorite: false,
    price: 20950,
    category: 'women',
  },
  {
    id: nanoid(),
    name: `Summer Tie Neck Long Dress`,
    description: 'Purple free Floral Dress',
    rating: 5,
    favorite: false,
    price: 10000,
    category: 'women',
  },
  {
    id: nanoid(),
    name: `Ladies Crystal Bracelet`,
    description: 'Silver Diamond Flower Bracelet',
    rating: 4,
    favorite: false,
    price: 3234,
    category: 'women',
  },
  {
    id: nanoid(),
    name: `Scarlet Darkness Dress`,
    description: 'Summer Square Neck Sleeveless',
    rating: 4,
    favorite: false,
    price: 10500,
    category: 'women',
  },
  {
    id: nanoid(),
    name: `Brown Crop Top SweatShirt`,
    description: 'Denami Women Diamond sweats',
    rating: 4,
    favorite: false,
    price: 9500,
    category: 'women',
  },
  {
    id: nanoid(),
    name: `Corporate High Heel`,
    description: 'Leather cover shoe - Black',
    rating: 5,
    favorite: false,
    price: 32000,
    category: 'women',
  },
];

export default products;
